# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'grpc_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_service.proto\x12\x0cgrpc_service\"\x1e\n\x0cGetJsonReply\x12\x0e\n\x06result\x18\x01 \x02(\t\" \n\x0eSubscribeReply\x12\x0e\n\x06result\x18\x01 \x02(\t\"\x1d\n\x0b\x43onfigReply\x12\x0e\n\x06result\x18\x01 \x02(\t\"[\n\x0bReportEvent\x12\x10\n\x08token_id\x18\x01 \x02(\t\x12\x13\n\x0bstream_name\x18\x02 \x02(\t\x12\x12\n\nevent_name\x18\x03 \x02(\t\x12\x11\n\tjson_text\x18\x04 \x02(\t\"$\n\x10GetReportRequest\x12\x10\n\x08token_id\x18\x01 \x02(\t\"3\n\x0cLoginRequest\x12\x11\n\tuser_name\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"\x1e\n\nLoginReply\x12\x10\n\x08token_id\x18\x01 \x02(\t\"!\n\rLogoutRequest\x12\x10\n\x08token_id\x18\x01 \x02(\t\"\x1d\n\x0bLogoutReply\x12\x0e\n\x06result\x18\x01 \x02(\t\"\'\n\x10SubscribeRequest\x12\x13\n\x0bstream_name\x18\x01 \x02(\t\"+\n\rCliConfigArgs\x12\r\n\x05ReqId\x18\x01 \x02(\x03\x12\x0b\n\x03\x63li\x18\x02 \x02(\t\"B\n\x0e\x43liConfigReply\x12\x10\n\x08ResReqId\x18\x01 \x02(\x03\x12\x0e\n\x06output\x18\x02 \x02(\t\x12\x0e\n\x06\x65rrors\x18\x03 \x02(\t\",\n\x0e\x44isplayCmdArgs\x12\r\n\x05ReqId\x18\x01 \x02(\x03\x12\x0b\n\x03\x63li\x18\x02 \x02(\t\"C\n\x0f\x44isplayCmdReply\x12\x10\n\x08ResReqId\x18\x01 \x02(\x03\x12\x0e\n\x06output\x18\x02 \x02(\t\x12\x0e\n\x06\x65rrors\x18\x03 \x02(\t2\xe1\x03\n\x0bGrpcService\x12?\n\x05Login\x12\x1a.grpc_service.LoginRequest\x1a\x18.grpc_service.LoginReply\"\x00\x12\x42\n\x06Logout\x12\x1b.grpc_service.LogoutRequest\x1a\x19.grpc_service.LogoutReply\"\x00\x12W\n\x15SubscribeByStreamName\x12\x1e.grpc_service.SubscribeRequest\x1a\x1c.grpc_service.SubscribeReply\"\x00\x12O\n\x0eGetEventReport\x12\x1e.grpc_service.GetReportRequest\x1a\x19.grpc_service.ReportEvent\"\x00\x30\x01\x12J\n\tCliConfig\x12\x1b.grpc_service.CliConfigArgs\x1a\x1c.grpc_service.CliConfigReply\"\x00\x30\x01\x12W\n\x14\x44isplayCmdTextOutput\x12\x1c.grpc_service.DisplayCmdArgs\x1a\x1d.grpc_service.DisplayCmdReply\"\x00\x30\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETJSONREPLY']._serialized_start=36
  _globals['_GETJSONREPLY']._serialized_end=66
  _globals['_SUBSCRIBEREPLY']._serialized_start=68
  _globals['_SUBSCRIBEREPLY']._serialized_end=100
  _globals['_CONFIGREPLY']._serialized_start=102
  _globals['_CONFIGREPLY']._serialized_end=131
  _globals['_REPORTEVENT']._serialized_start=133
  _globals['_REPORTEVENT']._serialized_end=224
  _globals['_GETREPORTREQUEST']._serialized_start=226
  _globals['_GETREPORTREQUEST']._serialized_end=262
  _globals['_LOGINREQUEST']._serialized_start=264
  _globals['_LOGINREQUEST']._serialized_end=315
  _globals['_LOGINREPLY']._serialized_start=317
  _globals['_LOGINREPLY']._serialized_end=347
  _globals['_LOGOUTREQUEST']._serialized_start=349
  _globals['_LOGOUTREQUEST']._serialized_end=382
  _globals['_LOGOUTREPLY']._serialized_start=384
  _globals['_LOGOUTREPLY']._serialized_end=413
  _globals['_SUBSCRIBEREQUEST']._serialized_start=415
  _globals['_SUBSCRIBEREQUEST']._serialized_end=454
  _globals['_CLICONFIGARGS']._serialized_start=456
  _globals['_CLICONFIGARGS']._serialized_end=499
  _globals['_CLICONFIGREPLY']._serialized_start=501
  _globals['_CLICONFIGREPLY']._serialized_end=567
  _globals['_DISPLAYCMDARGS']._serialized_start=569
  _globals['_DISPLAYCMDARGS']._serialized_end=613
  _globals['_DISPLAYCMDREPLY']._serialized_start=615
  _globals['_DISPLAYCMDREPLY']._serialized_end=682
  _globals['_GRPCSERVICE']._serialized_start=685
  _globals['_GRPCSERVICE']._serialized_end=1166
# @@protoc_insertion_point(module_scope)
