# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_service_pb2 as grpc__service__pb2

GRPC_GENERATED_VERSION = '1.74.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/grpc_service.GrpcService/Login',
                request_serializer=grpc__service__pb2.LoginRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.LoginReply.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/grpc_service.GrpcService/Logout',
                request_serializer=grpc__service__pb2.LogoutRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.LogoutReply.FromString,
                _registered_method=True)
        self.SubscribeByStreamName = channel.unary_unary(
                '/grpc_service.GrpcService/SubscribeByStreamName',
                request_serializer=grpc__service__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.SubscribeReply.FromString,
                _registered_method=True)
        self.GetEventReport = channel.unary_stream(
                '/grpc_service.GrpcService/GetEventReport',
                request_serializer=grpc__service__pb2.GetReportRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.ReportEvent.FromString,
                _registered_method=True)
        self.CliConfig = channel.unary_stream(
                '/grpc_service.GrpcService/CliConfig',
                request_serializer=grpc__service__pb2.CliConfigArgs.SerializeToString,
                response_deserializer=grpc__service__pb2.CliConfigReply.FromString,
                _registered_method=True)
        self.DisplayCmdTextOutput = channel.unary_stream(
                '/grpc_service.GrpcService/DisplayCmdTextOutput',
                request_serializer=grpc__service__pb2.DisplayCmdArgs.SerializeToString,
                response_deserializer=grpc__service__pb2.DisplayCmdReply.FromString,
                _registered_method=True)


class GrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeByStreamName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CliConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayCmdTextOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=grpc__service__pb2.LoginRequest.FromString,
                    response_serializer=grpc__service__pb2.LoginReply.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=grpc__service__pb2.LogoutRequest.FromString,
                    response_serializer=grpc__service__pb2.LogoutReply.SerializeToString,
            ),
            'SubscribeByStreamName': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeByStreamName,
                    request_deserializer=grpc__service__pb2.SubscribeRequest.FromString,
                    response_serializer=grpc__service__pb2.SubscribeReply.SerializeToString,
            ),
            'GetEventReport': grpc.unary_stream_rpc_method_handler(
                    servicer.GetEventReport,
                    request_deserializer=grpc__service__pb2.GetReportRequest.FromString,
                    response_serializer=grpc__service__pb2.ReportEvent.SerializeToString,
            ),
            'CliConfig': grpc.unary_stream_rpc_method_handler(
                    servicer.CliConfig,
                    request_deserializer=grpc__service__pb2.CliConfigArgs.FromString,
                    response_serializer=grpc__service__pb2.CliConfigReply.SerializeToString,
            ),
            'DisplayCmdTextOutput': grpc.unary_stream_rpc_method_handler(
                    servicer.DisplayCmdTextOutput,
                    request_deserializer=grpc__service__pb2.DisplayCmdArgs.FromString,
                    response_serializer=grpc__service__pb2.DisplayCmdReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_service.GrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_service.GrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GrpcService/Login',
            grpc__service__pb2.LoginRequest.SerializeToString,
            grpc__service__pb2.LoginReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GrpcService/Logout',
            grpc__service__pb2.LogoutRequest.SerializeToString,
            grpc__service__pb2.LogoutReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeByStreamName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_service.GrpcService/SubscribeByStreamName',
            grpc__service__pb2.SubscribeRequest.SerializeToString,
            grpc__service__pb2.SubscribeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc_service.GrpcService/GetEventReport',
            grpc__service__pb2.GetReportRequest.SerializeToString,
            grpc__service__pb2.ReportEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CliConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc_service.GrpcService/CliConfig',
            grpc__service__pb2.CliConfigArgs.SerializeToString,
            grpc__service__pb2.CliConfigReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayCmdTextOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc_service.GrpcService/DisplayCmdTextOutput',
            grpc__service__pb2.DisplayCmdArgs.SerializeToString,
            grpc__service__pb2.DisplayCmdReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
